data:
  input:
    root: "./dgame-test-data/"
  
experiment:
  id: "debug"
  outdir: 
  subjects: [
    "02",
    "pseudo02",
  ]
  objects: [
    'Kerze',
    'Vase',
    'Blume',
    'Tasse',
    'Rose',
  ]
  fillers: [
    'Tube',
    'Dose',
    'Flasche',
    'Pflanze',
    'Creme',
    'Spritze',
    'Paste',
  ]

analysis:
  matlab_root: ../dgame2/dg2_analysis/  # Path where MATLAB toolboxes/dependencies are mounted
  steps:
    # TODO rename to more understandable names and add short explanation of what each analysis stage does
    A_export_audio_and_et_times:
      enabled: true
    B_prepare_words:
      enabled: true
      case_insensitive: true
      skip_indices: # TODO these are indices after some processing, should use original raw indices instead
        "02_words_11.csv": [264, 268, 279]
        "05_words_11.csv": [9]
        "33_words_11.csv": [30, 323, 325]
    Ca_preproc_et_data:
      enabled: true
    Cb_preproc_fixations:
      enabled: true
    Cc_prepare_fixations_for_matlab:
      enabled: true
    Da_gaze_stats:
      enabled: true
      time_cluster_analysis: false
    Db_plot_descriptive_fixation:
      enabled: true
    F_preproc_EEG:
      enabled: true
      removed_electrodes: [  # channels that were removed to fit eyetracking glasses
        'FTT10h',
        'FTT9h',
        'FFT10h',
        'FFT9h',
      ]
    G_deconvolution_ERPs:
      enabled: true
    H_reconstruct_ERPs:
      enabled: true
