data:
  input:
    root: "./dgame-test-data/preproc"
    audio_dir: "audio/"
    eeg_dir: "eeg/"
    fixations_dir: "eyetracking/fixations/"
    gaze_dir: "eyetracking/gaze_positions/"
    surfaces_dir: "eyetracking/surfaces/"
    times_dir: "helper_files/"
    object_positions: "object_positions/"
  
experiment:
  id: "debug"
  outdir: 
  subjects: [
    "02",
    "pseudo02",
  ]
  objects: [
    'Kerze',
    'Vase',
    'Blume',
    'Tasse',
    'Rose',
  ]
  fillers: [
    'Tube',
    'Dose',
    'Flasche',
    'Pflanze',
    'Creme',
    'Spritze',
    'Paste',
  ]
  # TODO make case-insensitive by default?
  case_insensitive: true
  skip_indices: # TODO these are indices after some processing, should use original raw indices instead
    "02_words_11.csv": [264, 268, 279]
    "05_words_11.csv": [9]
    "33_words_11.csv": [30, 323, 325]

analysis:
  time_cluster_analysis: false
